<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>爬虫 on 搬砖工的日常</title>
    <link>https://rgozi.com/tags/%E7%88%AC%E8%99%AB/</link>
    <description>Recent content in 爬虫 on 搬砖工的日常</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>zh-cn</language>
    <lastBuildDate>Sun, 29 Jan 2017 11:11:12 +0000</lastBuildDate><atom:link href="https://rgozi.com/tags/%E7%88%AC%E8%99%AB/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>requests库的Failed to establish a new connection</title>
      <link>https://rgozi.com/post/requests%E5%BA%93error/</link>
      <pubDate>Sun, 29 Jan 2017 11:11:12 +0000</pubDate>
      
      <guid>https://rgozi.com/post/requests%E5%BA%93error/</guid>
      <description>&lt;p&gt;使用python做爬虫的过程中，经常会在较短的时间内构建大量的连接向服务器请求数据，遇到了这样的问题：&lt;/p&gt;
&lt;div class=&#34;highlight&#34;&gt;&lt;div class=&#34;chroma&#34;&gt;
&lt;table class=&#34;lntable&#34;&gt;&lt;tr&gt;&lt;td class=&#34;lntd&#34;&gt;
&lt;pre class=&#34;chroma&#34;&gt;&lt;code&gt;&lt;span class=&#34;lnt&#34;&gt;1
&lt;/span&gt;&lt;span class=&#34;lnt&#34;&gt;2
&lt;/span&gt;&lt;span class=&#34;lnt&#34;&gt;3
&lt;/span&gt;&lt;/code&gt;&lt;/pre&gt;&lt;/td&gt;
&lt;td class=&#34;lntd&#34;&gt;
&lt;pre class=&#34;chroma&#34;&gt;&lt;code class=&#34;language-fallback&#34; data-lang=&#34;fallback&#34;&gt;requests.exceptions.ConnectionError: HTTPConnectionPool(host=&amp;#39;xxx&amp;#39;, port=80):
Max retries exceeded with url: /document/record/_search?pretty=true (Caused by NewConnectionError
(&amp;#39;&amp;lt;requests.packages.urllib3.connection.HTTPConnection object at 0x7f544af9a5d0&amp;gt;: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution&amp;#39;,))
&lt;/code&gt;&lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;
&lt;/div&gt;
&lt;/div&gt;</description>
    </item>
    
  </channel>
</rss>
